server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pilipili
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2432757689

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pilipili.pilipiliback.entity

app:
  avatar:
    upload-dir: /Users/hanlelin/Desktop/pilipili/avatars/
  cover:
    upload-dir: /Users/hanlelin/Desktop/pilipili/covers/
  video:
    upload-dir: /Users/hanlelin/Desktop/pilipili/videos/

