server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2432757689
#  web:
#    resources:
#      static-locations: file:/Users/hanlelin/Desktop/pilipili/imgs
#  mvc:
#    path-match:
#      matching-strategy: ant_path_matcher
#    static-path-pattern: /imgs/**

app:
  avatar:
    upload-dir: /Users/hanlelin/Desktop/pilipili/avatars/
  cover:
    upload-dir: /Users/hanlelin/Desktop/pilipili/covers/
  video:
    upload-dir: /Users/hanlelin/Desktop/pilipili/videos/

